version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: fastapi-spotilike
    ports:
      - "5432:5432"
