name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Déclencheur pour chaque push sur la branche main
  tags:
    - 'v*'  # Déclencheur pour chaque tag commençant par 'v'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest  # L'agent exécutant le job

    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Connexion au GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 3. Construire l'image Docker
      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/my-app
          docker build -t $IMAGE_NAME:${{ github.ref_name }} .
          docker tag $IMAGE_NAME:${{ github.ref_name }} $IMAGE_NAME:latest

      # 4. Pousser l'image Docker
      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/my-app
          docker push $IMAGE_NAME:${{ github.ref_name }}
          docker push $IMAGE_NAME:latest
